classes/local/skel/version_php_file.php
=> Validate version number

cli/generate.php
Specifying a target directory is not yet implemented, pending the result of #22
=> Add cli script

classes/local/util/manager.php, skel/file/db_messages.mustache, tests/message_providers_test.php
Depending on the result of #15 and #18 I'll implement the skel class db_messages_file.
=> Message_providers feature

classes/local/skel/php_cli_file.php, classes/local/skel/php_web_file.php, skel/common/boilerplate_php.mustache
=> Add php_cli_file and php_web_file skel base types

classes/local/util/manager.php, cli/generate.php, locallib.php
=> Display log levels and write the files to the target directory

classes/local/skel/locallib_php_file.php, classes/local/skel/observer_file.php, classes/local/util/manager.php, skel/file/classes_observer.mustache, skel/file/db_events.mustache, skel/file/locallib.mustache, tests/observers_test.php
The pull request is split into three commits to be able to modify the way I create more than one file from the same template - see #13.
manager.php will conflict with #24.
=> Observers feature

classes/local/util/mustache.php, skel/file/db_access.mustache, skel/file/db_install.mustache, skel/file/db_messages.mustache, skel/file/db_uninstall.mustache, skel/file/db_upgrade.mustache, skel/file/db_upgradelib.mustache, skel/file/lang.mustache, skel/file/version.mustache
'@category' tag has also been added to some templates.
=> Use PRAGMA_ANCHORED_DOT

classes/local/util/manager.php, skel/file/classes_event_event.mustache, skel/file/db_events.mustache, tests/events_test.php
The manager.php file will conflict with #21.
Also, lines 176 to 178 from manager.php should probably be moved to a classes_event_php_file skel class.
I made this pull request so there are two examples (this and #21) of my idea for creating multiple files from the same template.
The template and the tests won't be affected by #13.
=> Events feature

classes/local/skel/mobile_php_file.php, classes/local/util/manager.php, skel/file/db_mobile.mustache, tests/mobile_addons_test.php
This is in preparation for generating a mod plugin type.
=> Mobile_addons feature

classes/local/util/manager.php, skel/file/cli.mustache, tests/cli_scripts_test.php
Modified as per #35.
I'll make another pull request for the example recipe because I've added example for other features that were also merged.
=> Cli_scripts feature

cli/example.yaml
The features 'cli_scripts', 'observers', 'mobile_addons' and 'events' have been
added to the recipe.
=> Update example recipe

skel/file/version.mustache, tests/version_php_test.php
For activity modules the component is 'mod_modname'.
=> Generate component in version.php correctly

classes/local/util/manager.php, cli/block.yaml, skel/file/block/block.mustache, skel/file/block/edit_form.mustache, tests/block_test.php
Generated a block and installed it, it works.
=> Block plugin type

classes/local/util/manager.php, cli/theme.yaml, skel/file/theme/config.mustache, skel/file/theme/layout.mustache, skel/file/theme/stylesheet.mustache, tests/theme_test.php
I've installed the generated plugin in my Moodle installation, it works (although it looks horrible).
=> Theme plugin type

classes/local/skel/lang_file.php, classes/local/util/manager.php, cli/example.yaml, skel/file/atto/button_js.mustache, skel/file/atto/lib.mustache, skel/file/block/backup/moodle2/backup_stepslib.mustache, skel/file/block/backup/moodle2/restore_stepslib.mustache, skel/file/block/block.mustache, skel/file/lang.mustache, skel/file/mod/backup/moodle2/backup_stepslib.mustache, skel/file/mod/backup/moodle2/restore_stepslib.mustache, skel/file/theme/config.mustache, tests/atto_test.php, tests/block_test.php, tests/cli_scripts_test.php, tests/lang_test.php, tests/mod_test.php, tests/phpunit_tests_test.php, tests/qtype_test.php, tests/theme_test.php
The commit messages are self-explanatory.
=> Recipe patch

classes/local/skel/base.php, classes/local/util/manager.php, cli/example.yaml, skel/file/enrol/lib.mustache, tests/enrol_test.php
There's not much documentation (on the docs) about creating an enrol plugin. And starting from Moodle 3.1 there's a standard UI for enrol plugins, so I've decided to use this standard UI.
=> Enrol plugin type

classes/local/util/manager.php, cli/example.yaml, lang/en/tool_pluginskel.php, tests/block_test.php, tests/capabilities_test.php, tests/enrol_test.php, tests/mod_test.php
The lang string containing the title will be generated automatically.
As per #66.
=> Add 'title' field to capabilities

classes/local/util/manager.php, cli/example.yaml, tests/atto_test.php
The corresponding lang string will be generated automatically.
=> Add 'text' field to strings_for_js

classes/local/util/manager.php, cli/example.yaml, lang/en/tool_pluginskel.php, tests/auth_test.php
The lang string 'auth_description' will be generated from this field.
=> Add 'description' field to auth_features

skel/file/mod/lib.mustache, skel/file/mod/mod_form.mustache, skel/file/mod/view.mustache
Addresses #94 
See also questions in https://github.com/mudrd8mz/moodle-tool_pluginskel/issues/94#issuecomment-540577186
=> Bugfix mod_ templates #94

CHANGES.md
=> Fixes typo in CHANGES.md

classes/local/util/manager.php, cli/example.yaml, lang/en/tool_pluginskel.php, skel/common/boilerplate_amd_js.mustache, skel/file/tiny/commands_js.mustache, skel/file/tiny/common_js.mustache, skel/file/tiny/configuration_js.mustache, skel/file/tiny/options_js.mustache, skel/file/tiny/plugin_js.mustache, skel/file/tiny/plugininfo_php.mustache, tests/tiny_testcase.php
This is still a work-in-progress, but I wanted to put it out there to start with.
Currently missing:
* unit tests
* some strings for the UI
* some changes to the Tiny API which I may make shortly.
=> Add generator for Tiny plugintype

classes/local/skel/base.php, classes/local/skel/external_function_file.php, classes/local/skel/lib_php_file.php, classes/local/skel/locallib_php_file.php, classes/local/skel/observer_file.php, classes/local/skel/phpunit_test_file.php
Detected whilst running phpstan on moodle core.
=> Fix incorrect class names
